on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Testing Wattspeed Action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wattspeed action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          token: '6qQUdH1Ayk3fQTagxFPBBYafvcIgg26hdJ98rKGXtXAnClUNBCsbUXE1OOD9TixT'
      - name: Get the response
        run: echo "The time was ${{ steps.test.outputs.response }}"
